### ISSUE TITLE
Exiting localrc hook - undo localrc modification when changing directory outside of project dir

### ISSUE THREAD

**Issue by MartyLake** [thinca/vim-localrc#11]
Hello,
Thanks for creating such a plugin ! It works great!

In a new project, I need to maintain multiple git-worktree of the same repository. 

I wanted to add something like this to the local.vimrc:
`set path+=absolute/path/to/specific/worktree/internal/include/dir`

But if I do that, and happen to switch to a new worktree with the same instance of vim, I will end up with different worktree in the same vim-path, then shortcuts like `gF` would go outside of the current worktree (which I want to avoid).

One way to solve this is to have some "local exit hook" where I could add the inverse operation
`set path-=absolute/path/to/specific/worktree/internal/include/dir`

There may be other options that would not require adding such a feature, however I don't know how to properly use vimscript to do this. Maybe it's a sign of fate that I need to invest in learning more vimscript ! :)

Best,

**Comment by thinca** [comment]
`'path'` option can have a buffer local value.
Could you try `setlocal` instead of `set`?
