### ISSUE TITLE
vim takes a long time to open the global vimrc

### ISSUE THREAD

**Issue by abid-mujtaba** [thinca/vim-localrc#8]
I often use vim to edit its own global vimrc (`vim ~/.vim/vimrc`). Of late vim has been taking very long to open this file (everything else opens just fine).

I speculate that this is being caused by some sort of recursion as this plugin searches for local vimrc while scanning the folder containing the global vimrc.

**Comment by thinca** [comment]
In default, `g:localrc_filename` is `.local.vimrc` so `~/.vim/vimrc` is never sourced.

Maybe this problem depends on your environment.

Could you take a profile? `+profile` feature is only available with Huge version of Vim.

```
# starting Vim
$ vim
```

Execute commands in Vim:
```
:profile start /path/to/result.txt
:profile! file */localrc.vim
:e ~/.vim/vimrc
:qa!
```

And put `result.txt` here.
